
# site details
name: Open Pencil
url: http://openpencil.github.io
description: Code. Documentation. Research.
avatar: https://avatars3.githubusercontent.com/u/1999668?v=2&s=70

# Conversion
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
    - generate_toc
  toc_token: "!TOC"
highlighter: pygments

email: jyoti.shankar@icloud.com
github: openpencil
